### ISSUE TITLE
wrong directions

### ISSUE THREAD

**Issue by arranka** [Dwerg/walletaid#5]
I've been testing wallets, the script returns me public addresses with its private, but none matches the wallet addresses.
It is a script that only generates private addresses with its public key.
Doesn't read wallet.dat files

**Comment by arranka** [comment]
see the proof
does not read wallet.dat only makes up random addresses

![image](https://user-images.githubusercontent.com/30248115/111859832-7634d780-8922-11eb-8f13-a8c9dd4b5578.png)

**Comment by Dwerg** [comment]
Your wallet shows uncompressed addresses, by default the script formats everything as compressed. You can change this parameter in the config.ini, just set "compressed = no" instead of yes.

If you uncompress the first one on the list you'll see it's an exact match. Note that the public key in hex is identical apart from a prefix of 02 or 04 (which is what makes the difference on the resulting address).
![Screenshot_20210504-034013_Chrome](https://user-images.githubusercontent.com/35254268/116952644-70eddb00-ac8b-11eb-9f50-37c1c711c06b.jpg)
